### ISSUE TITLE
Is supported the change of host and port ?

### ISSUE THREAD

**Issue by oliverhr** [js-data/js-data-redis#8]
On sources index:39

```
this.client = redis.createClient(this.defaults);
```

on node_redis [documentation](https://github.com/NodeRedis/node_redis#overloading):

> redis.createClient(options) is equivalent to redis.createClient(6379, '127.0.0.1', options)

**Comment by jmdobry** [comment]
I'll fix it as soon as I get a machine I can develop on (~2 weeks).

**Comment by oliverhr** [comment]
By the way, I have a problem running the tests, its looks that travis is having the same issue.

> Error: version not found: babel-core@5.6.17

PR created https://github.com/js-data/js-data-redis/pull/9

**Comment by oliverhr** [comment]
Ok, done again

PR https://github.com/js-data/js-data-redis/pull/10

**Comment by oliverhr** [comment]
Any news on this ?
